development:
 db_dump_on: 20

#   adapter: sqlite3
#   database: dbaudit/audit_development.sqlite3
#   pool: 5
#   timeout: 5000
test:
#   adapter: sqlite3
#   database: dbaudit/audit_test.sqlite3
#   pool: 5
#   timeout: 5000
production:
#   adapter: sqlite3
#   database: dbaudit/audit_production.sqlite3
#   pool: 5
#   timeout: 5000

